In [ ]:
#MODEL means-->regression model(line/curve/prediction line calculated by finding correlation from data ie;by finding patterns from data)....classification model-->(line/curve/decision boundary calculated by finding correlation from data ie;by finding patterns from data)
#MODEL BASED LEARNING means-->understanding the concept from given data(ie;estimating relationship b/n  given data and representing in terms of line/curve eq and this is only model)
#thus draw a model(line/curve) w.r.t learned concept.given data(means train data )...therefore at the time of testing we have model(line/curve/prediction line/decision boundary),we dont have training data,,,thus w.r.t this learned concept from training data(means derived line/curve/prediction line (for regression) or derived descision boundary(for classification))),,the oucome of test data is predicted
#model is byproduct of train data(ie;model(line/curve calculated by learning train data)
#EX-->Linear reg,poly reg,svmr,DTR,logistic reg(for class),DTC,svmc

#INSTANCE BASED LEARNING-->means RATTABAZII(memorizing ,,means not understanding concept from train data).,,thus NO LEARNING TAKESPLACE(ie;calculating eq of line/curve w.r.t train data not takes plaec)....given trained data(X_train) is memorized(means->plotted on graph,,but doesnt calculate equations for line/curve that describe the relationship b/n train data)given data,,thus if any unseen data(test data comes then we will predict the otcome w.r.t memorized data(X_train,y_train)),,,exactly same knn will do,,->calculate the dist b/n new data pt and nearest pt(given data(memorized data/X_train,y_train)) ,,and thus majority nearest pt belonging class is assigned to this new data pt as outcome(prediction)
#KNN IS A INSTANCE BASED LEARNING ,,,
#bcz it doesnt understand/learn the concept from data(ie;doesnt draw any decision/prediction line/curve),,just plot the data on graph(2d,3d..nd w.r.t dataset shape)
#when new i/p comes(unseen data/test data),at that time it will decide the outcome of this data,by checking the memorized data(given data ,,generally wi give X_train,y_train)
#EX-> k-nearest neighbors algorithm, kernel machines and RBF networks.
#bcz we are predicting outcome of new data(instance)(test data/unseen data) as it arrives by comaparing with )given data/X_train,y_train,,,thus named Instance based learning
##EX-> k-nearest neighbors algorithm, kernel machines and RBF networks.

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.datasets import load_breast_cancer
data=load_breast_cancer()
data.data#2d array

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [3]:
df=pd.DataFrame(np.c_[data.data,data.target],columns=[list(data.feature_names)+['target']])#np.c_  for conacatination of  ind and dep feature
df.head()

mean radius mean texture mean perimeter mean area mean smoothness  \
0       17.99        10.38         122.80    1001.0         0.11840   
1       20.57        17.77         132.90    1326.0         0.08474   
2       19.69        21.25         130.00    1203.0         0.10960   
3       11.42        20.38          77.58     386.1         0.14250   
4       20.29        14.34         135.10    1297.0         0.10030   

  mean compactness mean concavity mean concave points mean symmetry  \
0          0.27760         0.3001             0.14710        0.2419   
1          0.07864         0.0869             0.07017        0.1812   
2          0.15990         0.1974             0.12790        0.2069   
3          0.28390         0.2414             0.10520        0.2597   
4          0.13280         0.1980             0.10430        0.1809   

  mean fractal dimension  ... worst texture worst perimeter worst area  \
0                0.07871  ...         17.33          184.60     2019.0   
1                0.05667  ...         23.41          158.80     1956.0   
2                0.05999  ...         25.53          152.50     1709.0   
3                0.09744  ...         26.50           98.87      567.7   
4                0.05883  ...         16.67          152.20     1575.0   

  worst smoothness worst compactness worst concavity worst concave points  \
0           0.1622            0.6656          0.7119               0.2654   
1           0.1238            0.1866          0.2416               0.1860   
2           0.1444            0.4245          0.4504               0.2430   
3           0.2098            0.8663          0.6869               0.2575   
4           0.1374            0.2050          0.4000               0.1625   

  worst symmetry worst fractal dimension target  
0         0.4601                 0.11890    0.0  
1         0.2750                 0.08902    0.0  
2         0.3613                 0.08758    0.0  
3         0.6638                 0.17300    0.0  
4         0.2364                 0.07678    0.0  

[5 rows x 31 columns]

In [4]:
X=df.iloc[:,0:-1]
y=df.iloc[:,-1]

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)#note untill random_state=1,,how many times u execute this statement that many times it will generate same train and test dataset as it is there while executing 1st time
print('shape of X_train=',X_train.shape)
print('shape of y_train=',y_train.shape)
print('shape of X_test=',X_test.shape)
print('shape of y_test=',y_test.shape)

shape of X_train= (455, 30)
shape of y_train= (455,)
shape of X_test= (114, 30)
shape of y_test= (114,)


In [6]:
data.feature_names,data.target_names

(array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
        'mean smoothness', 'mean compactness', 'mean concavity',
        'mean concave points', 'mean symmetry', 'mean fractal dimension',
        'radius error', 'texture error', 'perimeter error', 'area error',
        'smoothness error', 'compactness error', 'concavity error',
        'concave points error', 'symmetry error',
        'fractal dimension error', 'worst radius', 'worst texture',
        'worst perimeter', 'worst area', 'worst smoothness',
        'worst compactness', 'worst concavity', 'worst concave points',
        'worst symmetry', 'worst fractal dimension'], dtype='<U23'),
 array(['malignant', 'benign'], dtype='<U9'))

In [7]:
#malignant means effected,,,,,benign --> kindly/soft

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
classifier=KNeighborsClassifier(n_neighbors=5)


In [10]:
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [11]:
classifier.score(X_test,y_test)

0.9122807017543859

In [12]:
classifier.score(X_train,y_train)

0.9538461538461539

In [13]:
#as u see accuracy is very good(not exact and excellant)

In [14]:
patient1=X_test.iloc[0]
patient1

mean radius                 13.940000
mean texture                13.170000
mean perimeter              90.310000
mean area                  594.200000
mean smoothness              0.124800
mean compactness             0.097550
mean concavity               0.101000
mean concave points          0.066150
mean symmetry                0.197600
mean fractal dimension       0.064570
radius error                 0.546100
texture error                2.635000
perimeter error              4.091000
area error                  44.740000
smoothness error             0.010040
compactness error            0.032470
concavity error              0.047630
concave points error         0.028530
symmetry error               0.017150
fractal dimension error      0.005528
worst radius                14.620000
worst texture               15.380000
worst perimeter             94.520000
worst area                 653.300000
worst smoothness             0.139400
worst compactness            0.136400
worst concav

In [15]:
#above data is in 1d
patient1=np.array([patient1])
#now it is in 2d
patient1

array([[1.394e+01, 1.317e+01, 9.031e+01, 5.942e+02, 1.248e-01, 9.755e-02,
        1.010e-01, 6.615e-02, 1.976e-01, 6.457e-02, 5.461e-01, 2.635e+00,
        4.091e+00, 4.474e+01, 1.004e-02, 3.247e-02, 4.763e-02, 2.853e-02,
        1.715e-02, 5.528e-03, 1.462e+01, 1.538e+01, 9.452e+01, 6.533e+02,
        1.394e-01, 1.364e-01, 1.559e-01, 1.015e-01, 2.160e-01, 7.253e-02]])

In [16]:
classifier.predict(patient1)

array([1.])

In [17]:
y_test.iloc[0]

1.0

In [18]:
classifier.predict(X_test)

array([1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0.,
       0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1.,
       0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1.,
       0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0.])

In [19]:
np.array(y_test)

array([1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0.,
       0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1.,
       0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.])